// This file is auto-generated by @hey-api/openapi-ts

export const AdminCoverageResponseSchema = {
    properties: {
        total_files: {
            type: 'integer',
            title: 'Total Files'
        },
        by_level: {
            items: {
                '$ref': '#/components/schemas/ProcessingLevelCoverage'
            },
            type: 'array',
            title: 'By Level'
        }
    },
    type: 'object',
    required: ['total_files', 'by_level'],
    title: 'AdminCoverageResponse'
} as const;

export const Body_ingest_uploadSchema = {
    properties: {
        file: {
            anyOf: [
                {
                    type: 'string',
                    contentMediaType: 'application/octet-stream'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File'
        },
        files: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        contentMediaType: 'application/octet-stream'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Files'
        }
    },
    type: 'object',
    title: 'Body_ingest-upload'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ChatMessageSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        role: {
            '$ref': '#/components/schemas/ChatRole'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        message_metadata: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message Metadata'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['session_id', 'role', 'content'],
    title: 'ChatMessage'
} as const;

export const ChatMessageMetadataSchema = {
    properties: {
        trigger: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ChatTrigger'
                },
                {
                    type: 'null'
                }
            ]
        },
        gap_cell: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/GapCell'
                },
                {
                    type: 'null'
                }
            ]
        },
        mode: {
            '$ref': '#/components/schemas/ChatMode',
            default: 'auto'
        }
    },
    type: 'object',
    title: 'ChatMessageMetadata'
} as const;

export const ChatMessageRequestSchema = {
    properties: {
        content: {
            type: 'string',
            minLength: 1,
            title: 'Content'
        },
        metadata: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ChatMessageMetadata'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['content'],
    title: 'ChatMessageRequest'
} as const;

export const ChatModeSchema = {
    type: 'string',
    enum: ['auto', 'ontology', 'knowledge_graph'],
    title: 'ChatMode'
} as const;

export const ChatRoleSchema = {
    type: 'string',
    enum: ['user', 'assistant'],
    title: 'ChatRole'
} as const;

export const ChatSessionCreateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        }
    },
    type: 'object',
    title: 'ChatSessionCreate'
} as const;

export const ChatSessionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id'],
    title: 'ChatSessionPublic'
} as const;

export const ChatSessionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ChatSessionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ChatSessionsPublic'
} as const;

export const ChatTriggerSchema = {
    type: 'string',
    enum: ['gap_click', 'user_input'],
    title: 'ChatTrigger'
} as const;

export const CoverageCellSchema = {
    properties: {
        material: {
            type: 'string',
            title: 'Material'
        },
        property: {
            type: 'string',
            title: 'Property'
        },
        regime_bucket: {
            '$ref': '#/components/schemas/RegimeBucket'
        },
        experiment_count: {
            type: 'integer',
            title: 'Experiment Count'
        }
    },
    type: 'object',
    required: ['material', 'property', 'regime_bucket', 'experiment_count'],
    title: 'CoverageCell'
} as const;

export const CoverageResponseSchema = {
    properties: {
        cells: {
            items: {
                '$ref': '#/components/schemas/CoverageCell'
            },
            type: 'array',
            title: 'Cells'
        },
        materials: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Materials'
        },
        properties: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Properties'
        },
        regime_buckets: {
            items: {
                '$ref': '#/components/schemas/RegimeBucket'
            },
            type: 'array',
            title: 'Regime Buckets'
        }
    },
    type: 'object',
    required: ['cells', 'materials', 'properties', 'regime_buckets'],
    title: 'CoverageResponse'
} as const;

export const DocumentFileSummarySchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        filename: {
            type: 'string',
            title: 'Filename'
        },
        mime_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mime Type'
        },
        processing_level: {
            '$ref': '#/components/schemas/ProcessingLevel'
        },
        okf_raw_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Okf Raw Path'
        },
        uploaded_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Uploaded At'
        },
        latest_task_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/IngestStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        latest_task_progress: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Task Progress'
        },
        latest_task_stage: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Task Stage'
        },
        latest_task_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Task Error'
        }
    },
    type: 'object',
    required: ['id', 'filename', 'processing_level'],
    title: 'DocumentFileSummary'
} as const;

export const GapCellSchema = {
    properties: {
        material_id: {
            type: 'string',
            format: 'uuid',
            title: 'Material Id'
        },
        material: {
            type: 'string',
            title: 'Material'
        },
        property: {
            type: 'string',
            title: 'Property'
        },
        regime_bucket: {
            '$ref': '#/components/schemas/RegimeBucket'
        }
    },
    type: 'object',
    required: ['material_id', 'material', 'property', 'regime_bucket'],
    title: 'GapCell'
} as const;

export const GraphEdgeSchema = {
    properties: {
        source: {
            type: 'string',
            title: 'Source'
        },
        target: {
            type: 'string',
            title: 'Target'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        properties: {
            additionalProperties: true,
            type: 'object',
            title: 'Properties'
        }
    },
    type: 'object',
    required: ['source', 'target', 'type'],
    title: 'GraphEdge'
} as const;

export const GraphNodeSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        properties: {
            additionalProperties: true,
            type: 'object',
            title: 'Properties'
        }
    },
    type: 'object',
    required: ['id', 'label', 'type'],
    title: 'GraphNode'
} as const;

export const GraphQueryRequestSchema = {
    properties: {
        template_id: {
            type: 'string',
            title: 'Template Id'
        },
        params: {
            additionalProperties: true,
            type: 'object',
            title: 'Params'
        },
        max_depth: {
            type: 'integer',
            maximum: 5,
            minimum: 1,
            title: 'Max Depth',
            default: 3
        }
    },
    type: 'object',
    required: ['template_id'],
    title: 'GraphQueryRequest'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const IngestFileDetailResponseSchema = {
    properties: {
        document: {
            '$ref': '#/components/schemas/DocumentFileSummary'
        },
        history: {
            items: {
                '$ref': '#/components/schemas/IngestFileHistoryItem'
            },
            type: 'array',
            title: 'History'
        }
    },
    type: 'object',
    required: ['document', 'history'],
    title: 'IngestFileDetailResponse'
} as const;

export const IngestFileHistoryItemSchema = {
    properties: {
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        status: {
            '$ref': '#/components/schemas/IngestStatus'
        },
        stage_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stage Name'
        },
        progress: {
            type: 'number',
            title: 'Progress'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['task_id', 'status', 'progress'],
    title: 'IngestFileHistoryItem'
} as const;

export const IngestFilesResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DocumentFileSummary'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'IngestFilesResponse'
} as const;

export const IngestRunRequestSchema = {
    properties: {
        document_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Document Ids'
        },
        level: {
            '$ref': '#/components/schemas/ProcessingLevel',
            default: 'L1'
        }
    },
    type: 'object',
    title: 'IngestRunRequest'
} as const;

export const IngestStatusSchema = {
    type: 'string',
    enum: ['queued', 'parse', 'normalize', 'dedup_link', 'load', 'build_flat', 'embed', 'sync_neo4j', 'build_wiki', 'done', 'error'],
    title: 'IngestStatus'
} as const;

export const IngestUploadBatchResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DocumentFileSummary'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        task_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Task Id'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'IngestUploadBatchResponse',
    description: 'Ответ upload: L0 в MinIO/Postgres + сразу поставленная в очередь L1-обработка.'
} as const;

export const IngestUploadResponseSchema = {
    properties: {
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        status: {
            '$ref': '#/components/schemas/IngestStatus'
        },
        progress: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Progress',
            default: 0
        },
        stage_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stage Name'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['task_id', 'status'],
    title: 'IngestUploadResponse'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MetricsResponseSchema = {
    properties: {
        total_experiments: {
            type: 'integer',
            title: 'Total Experiments'
        },
        total_documents: {
            type: 'integer',
            title: 'Total Documents'
        },
        total_materials: {
            type: 'integer',
            title: 'Total Materials'
        },
        avg_response_time_seconds: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Response Time Seconds'
        },
        entity_extraction_f1: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Entity Extraction F1'
        },
        provenance_coverage: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Provenance Coverage',
            default: 1
        },
        graph_coverage: {
            anyOf: [
                {
                    type: 'number',
                    maximum: 1,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Graph Coverage'
        }
    },
    type: 'object',
    required: ['total_experiments', 'total_documents', 'total_materials'],
    title: 'MetricsResponse'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PathResponseSchema = {
    properties: {
        nodes: {
            items: {
                '$ref': '#/components/schemas/GraphNode'
            },
            type: 'array',
            title: 'Nodes'
        },
        edges: {
            items: {
                '$ref': '#/components/schemas/GraphEdge'
            },
            type: 'array',
            title: 'Edges'
        },
        path_length: {
            type: 'integer',
            title: 'Path Length'
        }
    },
    type: 'object',
    required: ['path_length'],
    title: 'PathResponse'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProcessingLevelSchema = {
    type: 'string',
    enum: ['L0', 'L1', 'L2', 'L3'],
    title: 'ProcessingLevel'
} as const;

export const ProcessingLevelCoverageSchema = {
    properties: {
        level: {
            '$ref': '#/components/schemas/ProcessingLevel'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        percent: {
            type: 'number',
            title: 'Percent'
        }
    },
    type: 'object',
    required: ['level', 'count', 'percent'],
    title: 'ProcessingLevelCoverage'
} as const;

export const RegimeBucketSchema = {
    type: 'string',
    enum: ['low', 'medium', 'high'],
    title: 'RegimeBucket'
} as const;

export const SubgraphResponseSchema = {
    properties: {
        nodes: {
            items: {
                '$ref': '#/components/schemas/GraphNode'
            },
            type: 'array',
            title: 'Nodes'
        },
        edges: {
            items: {
                '$ref': '#/components/schemas/GraphEdge'
            },
            type: 'array',
            title: 'Edges'
        }
    },
    type: 'object',
    title: 'SubgraphResponse'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WikiDocumentContentSchema = {
    properties: {
        okf_path: {
            type: 'string',
            title: 'Okf Path'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        display_path: {
            type: 'string',
            title: 'Display Path',
            description: 'Path relative to 01_docling_clean00/ for UI display.'
        },
        raw_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Raw Path',
            description: 'Concrete raw path under SHARED/ for the original document.'
        },
        markdown: {
            type: 'string',
            title: 'Markdown'
        }
    },
    type: 'object',
    required: ['okf_path', 'title', 'display_path', 'markdown'],
    title: 'WikiDocumentContent'
} as const;

export const WikiFileTreeNodeSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        type: {
            type: 'string',
            enum: ['dir', 'file'],
            title: 'Type'
        },
        path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Path',
            description: 'Relative path under SHARED/ for file nodes.'
        },
        children: {
            items: {
                '$ref': '#/components/schemas/WikiFileTreeNode'
            },
            type: 'array',
            title: 'Children'
        }
    },
    type: 'object',
    required: ['name', 'type'],
    title: 'WikiFileTreeNode'
} as const;

export const WikiSearchResponseSchema = {
    properties: {
        results: {
            items: {
                '$ref': '#/components/schemas/WikiSearchResult'
            },
            type: 'array',
            title: 'Results'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['results', 'total'],
    title: 'WikiSearchResponse'
} as const;

export const WikiSearchResultSchema = {
    properties: {
        okf_path: {
            type: 'string',
            title: 'Okf Path'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        snippet: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Snippet'
        }
    },
    type: 'object',
    required: ['okf_path', 'title'],
    title: 'WikiSearchResult'
} as const;

export const WikiTreeResponseSchema = {
    properties: {
        requested_root: {
            type: 'string',
            title: 'Requested Root'
        },
        resolved_root: {
            type: 'string',
            title: 'Resolved Root'
        },
        generated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Generated At'
        },
        children: {
            items: {
                '$ref': '#/components/schemas/WikiFileTreeNode'
            },
            type: 'array',
            title: 'Children',
            description: 'Top-level folders inside 01_docling_clean00/ (e.g. RAW_DATA, UPLOAD_DATA).'
        }
    },
    type: 'object',
    required: ['requested_root', 'resolved_root', 'generated_at'],
    title: 'WikiTreeResponse'
} as const;