// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { AdminAdminCoverageResponse, AnalyticsCoverageResponse, AnalyticsMetricsResponse, ChatListSessionsResponse, ChatCreateSessionData, ChatCreateSessionResponse, ChatGetSessionHistoryData, ChatGetSessionHistoryResponse, ChatDeleteSessionData, ChatDeleteSessionResponse, ChatPostMessageData, ChatPostMessageResponse, GraphQueryData, GraphQueryResponse, GraphSubgraphData, GraphSubgraphResponse, GraphPathData, GraphPathResponse, IngestUploadData, IngestUploadResponse2, IngestRunIngestData, IngestRunIngestResponse, IngestListFilesData, IngestListFilesResponse, IngestGetFileDetailData, IngestGetFileDetailResponse, IngestDeleteFileData, IngestDeleteFileResponse, IngestReindexResponse, IngestGetStatusData, IngestGetStatusResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, SourcesDownloadContentData, SourcesDownloadContentResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse, WikiGetTreeData, WikiGetTreeResponse, WikiSearchData, WikiSearchResponse2, WikiGetDocumentContentData, WikiGetDocumentContentResponse, WikiDownloadMarkdownData, WikiDownloadMarkdownResponse, WikiDownloadRawData, WikiDownloadRawResponse } from './types.gen';

export class AdminService {
    /**
     * Admin Coverage
     * GET /api/v1/admin/coverage — агрегат покрытия корпуса по L0..L3.
     * @returns AdminCoverageResponse Successful Response
     * @throws ApiError
     */
    public static adminCoverage(): CancelablePromise<AdminAdminCoverageResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/admin/coverage'
        });
    }
}

export class AnalyticsService {
    /**
     * Coverage
     * GET /api/v1/analytics/coverage — полная heatmap (заполненные + пустые ячейки).
     * @returns CoverageResponse Successful Response
     * @throws ApiError
     */
    public static coverage(): CancelablePromise<AnalyticsCoverageResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/analytics/coverage'
        });
    }
    
    /**
     * Metrics
     * GET /api/v1/metrics — KPI dashboard (SPEC_V3 §2).
     * @returns MetricsResponse Successful Response
     * @throws ApiError
     */
    public static metrics(): CancelablePromise<AnalyticsMetricsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/metrics'
        });
    }
}

export class ChatService {
    /**
     * List Sessions
     * GET /api/v1/chat/sessions — список сессий текущего пользователя.
     * @returns ChatSessionsPublic Successful Response
     * @throws ApiError
     */
    public static listSessions(): CancelablePromise<ChatListSessionsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/chat/sessions'
        });
    }
    
    /**
     * Create Session
     * POST /api/v1/chat/sessions — создать сессию (SPEC_V3 §8.4).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ChatSessionPublic Successful Response
     * @throws ApiError
     */
    public static createSession(data: ChatCreateSessionData): CancelablePromise<ChatCreateSessionResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/chat/sessions',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Session History
     * GET /api/v1/chat/sessions/{id} — история сессии (user/assistant сообщения).
     * @param data The data for the request.
     * @param data.sessionId
     * @returns ChatMessage Successful Response
     * @throws ApiError
     */
    public static getSessionHistory(data: ChatGetSessionHistoryData): CancelablePromise<ChatGetSessionHistoryResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/chat/sessions/{session_id}',
            path: {
                session_id: data.sessionId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Session
     * DELETE /api/v1/chat/sessions/{id} — удалить сессию и её сообщения.
     * @param data The data for the request.
     * @param data.sessionId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static deleteSession(data: ChatDeleteSessionData): CancelablePromise<ChatDeleteSessionResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/chat/sessions/{session_id}',
            path: {
                session_id: data.sessionId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Post Message
     * POST /api/v1/chat/sessions/{id}/messages — SSE stream (§8.4).
     *
     * nginx для `/api/v1/chat/` держит `proxy_buffering off` (см. frontend/nginx.conf).
     * TODO(SPEC_V3 §5.7): реальный token-by-token LLM-стриминг; сейчас один SSE-event
     * с полным JSON-ответом (`ChatMessageResponse`) после синхронной обработки.
     * @param data The data for the request.
     * @param data.sessionId
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static postMessage(data: ChatPostMessageData): CancelablePromise<ChatPostMessageResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/chat/sessions/{session_id}/messages',
            path: {
                session_id: data.sessionId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class GraphService {
    /**
     * Query
     * POST /api/v1/graph/query — запрос по шаблону, raw Cypher не принимается (§8.3).
     *
     * TODO(SPEC_V3 §5.3): библиотека Cypher-шаблонов (5-8 шт., потребуют `_session`
     * для реальных запросов); заглушка — пустой результат, БД пока не используется.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns SubgraphResponse Successful Response
     * @throws ApiError
     */
    public static query(data: GraphQueryData): CancelablePromise<GraphQueryResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/graph/query',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Subgraph
     * GET /api/v1/graph/subgraph/{entity_id} — SQL fallback вокруг эксперимента (§8.3).
     * @param data The data for the request.
     * @param data.entityId
     * @param data.depth
     * @returns SubgraphResponse Successful Response
     * @throws ApiError
     */
    public static subgraph(data: GraphSubgraphData): CancelablePromise<GraphSubgraphResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/graph/subgraph/{entity_id}',
            path: {
                entity_id: data.entityId
            },
            query: {
                depth: data.depth
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Path
     * GET /api/v1/graph/path (P2) — Neo4j down -> 503, без SQL fallback (§8.3).
     *
     * TODO(SPEC_V3 §8.3 P2): Neo4j `shortestPath`; заглушка возвращает пустой путь,
     * когда Neo4j доступен.
     * @param data The data for the request.
     * @param data._from
     * @param data.to
     * @param data.maxDepth
     * @returns PathResponse Successful Response
     * @throws ApiError
     */
    public static path(data: GraphPathData): CancelablePromise<GraphPathResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/graph/path',
            query: {
                from: data._from,
                to: data.to,
                max_depth: data.maxDepth
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class IngestService {
    /**
     * Upload
     * POST /api/v1/ingest/upload — parser SHARED + Document L0, сразу ставит L1-парсинг в очередь.
     * @param data The data for the request.
     * @param data.formData
     * @returns IngestUploadBatchResponse Successful Response
     * @throws ApiError
     */
    public static upload(data: IngestUploadData = {}): CancelablePromise<IngestUploadResponse2> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/ingest/upload',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Run Ingest
     * POST /api/v1/ingest/run — (пере)запуск обработки на заданном уровне.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns IngestUploadResponse Successful Response
     * @throws ApiError
     */
    public static runIngest(data: IngestRunIngestData): CancelablePromise<IngestRunIngestResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/ingest/run',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Files
     * GET /api/v1/ingest/files — список файлов и уровень обработки L0..L3.
     * @param data The data for the request.
     * @param data.processingLevel
     * @param data.limit
     * @param data.offset
     * @returns IngestFilesResponse Successful Response
     * @throws ApiError
     */
    public static listFiles(data: IngestListFilesData = {}): CancelablePromise<IngestListFilesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/ingest/files',
            query: {
                processing_level: data.processingLevel,
                limit: data.limit,
                offset: data.offset
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get File Detail
     * GET /api/v1/ingest/files/{id} — метаданные + история задач.
     * @param data The data for the request.
     * @param data.documentId
     * @returns IngestFileDetailResponse Successful Response
     * @throws ApiError
     */
    public static getFileDetail(data: IngestGetFileDetailData): CancelablePromise<IngestGetFileDetailResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/ingest/files/{document_id}',
            path: {
                document_id: data.documentId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete File
     * DELETE /api/v1/ingest/files/{id} — удалить запись Document из БД.
     * @param data The data for the request.
     * @param data.documentId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static deleteFile(data: IngestDeleteFileData): CancelablePromise<IngestDeleteFileResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/ingest/files/{document_id}',
            path: {
                document_id: data.documentId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reindex
     * POST /api/v1/ingest/reindex — полная переиндексация (not implemented yet).
     * @returns IngestUploadResponse Successful Response
     * @throws ApiError
     */
    public static reindex(): CancelablePromise<IngestReindexResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/ingest/reindex'
        });
    }
    
    /**
     * Get Status
     * GET /api/v1/ingest/status/{task_id} — статус из Postgres.
     * @param data The data for the request.
     * @param data.taskId
     * @returns IngestUploadResponse Successful Response
     * @throws ApiError
     */
    public static getStatus(data: IngestGetStatusData): CancelablePromise<IngestGetStatusResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/ingest/status/{task_id}',
            path: {
                task_id: data.taskId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class SourcesService {
    /**
     * Download Content
     * Stream raw document bytes from parser SHARED through the API.
     * @param data The data for the request.
     * @param data.docId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static downloadContent(data: SourcesDownloadContentData): CancelablePromise<SourcesDownloadContentResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sources/{doc_id}/content',
            path: {
                doc_id: data.docId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}

export class WikiService {
    /**
     * Get Tree
     * GET /api/v1/wiki/tree — processed markdown folder tree from parser SHARED/.
     * @param data The data for the request.
     * @param data.root Subtree relative to SHARED/, default is cleaned Docling markdown.
     * @param data.maxDepth
     * @returns WikiTreeResponse Successful Response
     * @throws ApiError
     */
    public static getTree(data: WikiGetTreeData = {}): CancelablePromise<WikiGetTreeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/wiki/tree',
            query: {
                root: data.root,
                max_depth: data.maxDepth
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Search
     * GET /api/v1/wiki/search — find processed markdown files by filename/path.
     * @param data The data for the request.
     * @param data.q
     * @returns WikiSearchResponse Successful Response
     * @throws ApiError
     */
    public static search(data: WikiSearchData): CancelablePromise<WikiSearchResponse2> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/wiki/search',
            query: {
                q: data.q
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Document Content
     * GET /api/v1/wiki/documents/content — read cleaned markdown for display.
     * @param data The data for the request.
     * @param data.okfPath OKF path under SHARED/, e.g. 01_docling_clean00/UPLOAD_DATA/reports/q1.pdf.md
     * @returns WikiDocumentContent Successful Response
     * @throws ApiError
     */
    public static getDocumentContent(data: WikiGetDocumentContentData): CancelablePromise<WikiGetDocumentContentResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/wiki/documents/content',
            query: {
                okf_path: data.okfPath
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Download Markdown
     * Download cleaned markdown file.
     * @param data The data for the request.
     * @param data.okfPath OKF path under SHARED/.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static downloadMarkdown(data: WikiDownloadMarkdownData): CancelablePromise<WikiDownloadMarkdownResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/wiki/documents/download/markdown',
            query: {
                okf_path: data.okfPath
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Download Raw
     * Download the original raw document for a processed markdown file.
     * @param data The data for the request.
     * @param data.okfPath OKF path under SHARED/.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static downloadRaw(data: WikiDownloadRawData): CancelablePromise<WikiDownloadRawResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/wiki/documents/download/raw',
            query: {
                okf_path: data.okfPath
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}