// This file is auto-generated by @hey-api/openapi-ts

export type AdminCoverageResponse = {
    total_files: number;
    by_level: Array<ProcessingLevelCoverage>;
};

export type Body_ingest_upload = {
    file?: (string | null);
    files?: (Array<(string)> | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChatMessage = {
    id?: string;
    session_id: string;
    role: ChatRole;
    content: string;
    message_metadata?: ({
    [key: string]: unknown;
} | null);
    created_at?: (string | null);
};

export type ChatMessageMetadata = {
    trigger?: (ChatTrigger | null);
    gap_cell?: (GapCell | null);
    mode?: ChatMode;
};

export type ChatMessageRequest = {
    content: string;
    metadata?: (ChatMessageMetadata | null);
};

export type ChatMode = 'auto' | 'ontology' | 'knowledge_graph';

export type ChatRole = 'user' | 'assistant';

export type ChatSessionCreate = {
    title?: (string | null);
};

export type ChatSessionPublic = {
    id: string;
    title?: (string | null);
    created_at?: (string | null);
};

export type ChatSessionsPublic = {
    data: Array<ChatSessionPublic>;
    count: number;
};

export type ChatTrigger = 'gap_click' | 'user_input';

export type CoverageCell = {
    material: string;
    property: string;
    regime_bucket: RegimeBucket;
    experiment_count: number;
};

export type CoverageResponse = {
    cells: Array<CoverageCell>;
    materials: Array<(string)>;
    properties: Array<(string)>;
    regime_buckets: Array<RegimeBucket>;
};

export type DocumentFileSummary = {
    id: string;
    filename: string;
    mime_type?: (string | null);
    processing_level: ProcessingLevel;
    okf_raw_path?: (string | null);
    uploaded_at?: (string | null);
    latest_task_status?: (IngestStatus | null);
    latest_task_progress?: (number | null);
    latest_task_stage?: (string | null);
    latest_task_error?: (string | null);
};

export type GapCell = {
    material_id: string;
    material: string;
    property: string;
    regime_bucket: RegimeBucket;
};

export type GraphEdge = {
    source: string;
    target: string;
    type: string;
    properties?: {
        [key: string]: unknown;
    };
};

export type GraphNode = {
    id: string;
    label: string;
    type: string;
    properties?: {
        [key: string]: unknown;
    };
};

export type GraphQueryRequest = {
    template_id: string;
    params?: {
        [key: string]: unknown;
    };
    max_depth?: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IngestFileDetailResponse = {
    document: DocumentFileSummary;
    history: Array<IngestFileHistoryItem>;
};

export type IngestFileHistoryItem = {
    task_id: string;
    status: IngestStatus;
    stage_name?: (string | null);
    progress: number;
    error?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type IngestFilesResponse = {
    data: Array<DocumentFileSummary>;
    count: number;
};

export type IngestRunRequest = {
    document_ids?: Array<(string)>;
    level?: ProcessingLevel;
};

export type IngestStatus = 'queued' | 'parse' | 'normalize' | 'dedup_link' | 'load' | 'build_flat' | 'embed' | 'sync_neo4j' | 'build_wiki' | 'done' | 'error';

/**
 * Ответ upload: L0 в MinIO/Postgres + сразу поставленная в очередь L1-обработка.
 */
export type IngestUploadBatchResponse = {
    data: Array<DocumentFileSummary>;
    count: number;
    task_id?: (string | null);
};

export type IngestUploadResponse = {
    task_id: string;
    status: IngestStatus;
    progress?: number;
    stage_name?: (string | null);
    error?: (string | null);
};

export type Message = {
    message: string;
};

export type MetricsResponse = {
    total_experiments: number;
    total_documents: number;
    total_materials: number;
    avg_response_time_seconds?: (number | null);
    entity_extraction_f1?: (number | null);
    provenance_coverage?: number;
    graph_coverage?: (number | null);
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PathResponse = {
    nodes?: Array<GraphNode>;
    edges?: Array<GraphEdge>;
    path_length: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProcessingLevel = 'L0' | 'L1' | 'L2' | 'L3';

export type ProcessingLevelCoverage = {
    level: ProcessingLevel;
    count: number;
    percent: number;
};

export type RegimeBucket = 'low' | 'medium' | 'high';

export type SubgraphResponse = {
    nodes?: Array<GraphNode>;
    edges?: Array<GraphEdge>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WikiDocumentContent = {
    okf_path: string;
    title: string;
    /**
     * Path relative to 01_docling_clean00/ for UI display.
     */
    display_path: string;
    /**
     * Concrete raw path under SHARED/ for the original document.
     */
    raw_path?: (string | null);
    markdown: string;
};

export type WikiFileTreeNode = {
    name: string;
    type: 'dir' | 'file';
    /**
     * Relative path under SHARED/ for file nodes.
     */
    path?: (string | null);
    children?: Array<WikiFileTreeNode>;
};

export type type = 'dir' | 'file';

export type WikiSearchResponse = {
    results: Array<WikiSearchResult>;
    total: number;
};

export type WikiSearchResult = {
    okf_path: string;
    title: string;
    snippet?: (string | null);
};

export type WikiTreeResponse = {
    requested_root: string;
    resolved_root: string;
    generated_at: string;
    /**
     * Top-level folders inside 01_docling_clean00/ (e.g. RAW_DATA, UPLOAD_DATA).
     */
    children?: Array<WikiFileTreeNode>;
};

export type AdminAdminCoverageResponse = (AdminCoverageResponse);

export type AnalyticsCoverageResponse = (CoverageResponse);

export type AnalyticsMetricsResponse = (MetricsResponse);

export type ChatListSessionsResponse = (ChatSessionsPublic);

export type ChatCreateSessionData = {
    requestBody: ChatSessionCreate;
};

export type ChatCreateSessionResponse = (ChatSessionPublic);

export type ChatGetSessionHistoryData = {
    sessionId: string;
};

export type ChatGetSessionHistoryResponse = (Array<ChatMessage>);

export type ChatDeleteSessionData = {
    sessionId: string;
};

export type ChatDeleteSessionResponse = (void);

export type ChatPostMessageData = {
    requestBody: ChatMessageRequest;
    sessionId: string;
};

export type ChatPostMessageResponse = (unknown);

export type GraphQueryData = {
    requestBody: GraphQueryRequest;
};

export type GraphQueryResponse = (SubgraphResponse);

export type GraphSubgraphData = {
    depth?: number;
    entityId: string;
};

export type GraphSubgraphResponse = (SubgraphResponse);

export type GraphPathData = {
    _from: string;
    maxDepth?: number;
    to: string;
};

export type GraphPathResponse = (PathResponse);

export type IngestUploadData = {
    formData?: Body_ingest_upload;
};

export type IngestUploadResponse2 = (IngestUploadBatchResponse);

export type IngestRunIngestData = {
    requestBody: IngestRunRequest;
};

export type IngestRunIngestResponse = (IngestUploadResponse);

export type IngestListFilesData = {
    limit?: number;
    offset?: number;
    processingLevel?: (ProcessingLevel | null);
};

export type IngestListFilesResponse = (IngestFilesResponse);

export type IngestGetFileDetailData = {
    documentId: string;
};

export type IngestGetFileDetailResponse = (IngestFileDetailResponse);

export type IngestDeleteFileData = {
    documentId: string;
};

export type IngestDeleteFileResponse = (void);

export type IngestReindexResponse = (IngestUploadResponse);

export type IngestGetStatusData = {
    taskId: string;
};

export type IngestGetStatusResponse = (IngestUploadResponse);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SourcesDownloadContentData = {
    docId: string;
};

export type SourcesDownloadContentResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WikiGetTreeData = {
    maxDepth?: number;
    /**
     * Subtree relative to SHARED/, default is cleaned Docling markdown.
     */
    root?: string;
};

export type WikiGetTreeResponse = (WikiTreeResponse);

export type WikiSearchData = {
    q: string;
};

export type WikiSearchResponse2 = (WikiSearchResponse);

export type WikiGetDocumentContentData = {
    /**
     * OKF path under SHARED/, e.g. 01_docling_clean00/UPLOAD_DATA/reports/q1.pdf.md
     */
    okfPath: string;
};

export type WikiGetDocumentContentResponse = (WikiDocumentContent);

export type WikiDownloadMarkdownData = {
    /**
     * OKF path under SHARED/.
     */
    okfPath: string;
};

export type WikiDownloadMarkdownResponse = (unknown);

export type WikiDownloadRawData = {
    /**
     * OKF path under SHARED/.
     */
    okfPath: string;
};

export type WikiDownloadRawResponse = (unknown);