"""Loader for `data/entity_ruler_patterns.jsonl` — spaCy EntityRuler patterns
auto-generated by the `term_dictionary` tool (branch `feature/extraction-benchmark`,
not merged into `main`; copied here as a static snapshot, not a live dependency —
see `data/entity_ruler_patterns.jsonl` for provenance).

Only a minimal reader lives here — the source project's own `ontology_loader.py`
exposes a much larger API (`entity_aliases()`, `entity_same_as()`, ...) aimed at
`workers/etl`/Postgres, which this service has no use for.
"""

import json
from pathlib import Path

_PATTERNS_PATH = Path(__file__).parents[1] / "data" / "entity_ruler_patterns.jsonl"

# Only labels that exist in the source file AND have an unambiguous match in
# `science_kg.models.EntityType` are mapped. The source file only ever contains
# MATERIAL/PROCESS/PROPERTY/EQUIPMENT (verified against the actual data, not the
# source project's README) — nothing else to drop here in practice.
# term_dictionary's "PROCESS" label already matches our EntityType.PROCESS
# name 1:1 post-SPEC_V5 rename (was a REGIME remap before).
LABEL_MAP: dict[str, str] = {
    "MATERIAL": "MATERIAL",
    "EQUIPMENT": "EQUIPMENT",
    "PROCESS": "PROCESS",
    "PROPERTY": "PROPERTY",
}


def load_mapped_patterns() -> list[dict]:
    """Read entity_ruler_patterns.jsonl, remap labels via LABEL_MAP, drop the rest."""
    if not _PATTERNS_PATH.exists():
        return []

    patterns: list[dict] = []
    with _PATTERNS_PATH.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            label = LABEL_MAP.get(row["label"])
            if label is None:
                continue
            patterns.append({"label": label, "pattern": row["pattern"]})
    return patterns
