"""add litsearch tables

Revision ID: a43ee2bced5c
Revises: b2c3d4e5f6a7
Create Date: 2026-07-03 21:41:51.065306

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a43ee2bced5c'
down_revision = 'd3e4f5a6b7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('literature_searches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sa.Enum('SEARCHING', 'FETCHING', 'READING', 'DONE', 'FAILED', name='litstage'), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('followup_of', sa.Uuid(), nullable=True),
    sa.Column('followup_search_id', sa.Uuid(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='experiments'
    )
    op.create_index(op.f('ix_experiments_literature_searches_session_id'), 'literature_searches', ['session_id'], unique=False, schema='experiments')
    op.create_table('literature_papers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('search_id', sa.Uuid(), nullable=False),
    sa.Column('doi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('authors', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('abstract', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pdf_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('fetch_status', sa.Enum('PENDING', 'DOWNLOADING', 'DONE', 'FAILED', 'SKIPPED', name='fetchstatus'), nullable=False),
    sa.Column('fetch_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('object_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fulltext_status', sa.Enum('NONE', 'ADDED', 'FAILED', name='fulltextstatus'), nullable=False),
    sa.Column('fulltext_chars', sa.Integer(), nullable=False),
    sa.Column('ingest_status', sa.Enum('NONE', 'QUEUED', 'RUNNING', 'DONE', 'FAILED', name='litingeststatus'), nullable=False),
    sa.Column('ingest_task_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['experiments.documents.id'], ),
    sa.ForeignKeyConstraint(['search_id'], ['experiments.literature_searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id'),
    schema='experiments'
    )
    op.create_index(op.f('ix_experiments_literature_papers_search_id'), 'literature_papers', ['search_id'], unique=False, schema='experiments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experiments_literature_papers_search_id'), table_name='literature_papers', schema='experiments')
    op.drop_table('literature_papers', schema='experiments')
    op.drop_index(op.f('ix_experiments_literature_searches_session_id'), table_name='literature_searches', schema='experiments')
    op.drop_table('literature_searches', schema='experiments')
    # ### end Alembic commands ###
    # Autogenerate doesn't emit DROP TYPE for the enum columns above (Alembic
    # limitation on Postgres); drop them explicitly so downgrade->upgrade round-trips.
    sa.Enum(name='fetchstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='fulltextstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='litingeststatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='litstage').drop(op.get_bind(), checkfirst=True)
