"""add domain and chat tables

Revision ID: f8bfd1e20554
Revises: c98c486f2133
Create Date: 2026-07-02 13:11:12.208299

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8bfd1e20554'
down_revision = 'c98c486f2133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('minio_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='experiments'
    )
    op.create_table('entity_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='experiments'
    )
    op.create_table('entity_same_as',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='experiments'
    )
    op.create_table('ingest_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PARSE', 'NORMALIZE', 'DEDUP_LINK', 'LOAD', 'BUILD_FLAT', 'EMBED', 'SYNC_NEO4J', 'BUILD_WIKI', 'DONE', 'ERROR', name='ingeststatus'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('document_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='experiments'
    )
    op.create_table('labs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='experiments'
    )
    op.create_table('materials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('material_type', sa.Enum('ALLOY', 'COMPOUND', 'PURE_METAL', name='materialtype'), nullable=False),
    sa.Column('formula', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('composition', sa.JSON(), nullable=True),
    sa.Column('smiles', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='experiments'
    )
    op.create_table('properties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='experiments'
    )
    op.create_table('regimes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('medium', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='experiments'
    )
    op.create_table('chat_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lab_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['experiments.labs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='experiments'
    )
    op.create_table('researchers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lab_id', sa.Uuid(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['experiments.labs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='experiments'
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='chatrole'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('material_id', sa.Uuid(), nullable=True),
    sa.Column('regime_id', sa.Uuid(), nullable=True),
    sa.Column('equipment_id', sa.Uuid(), nullable=True),
    sa.Column('lab_id', sa.Uuid(), nullable=True),
    sa.Column('researcher_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_anchor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grouping_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_paragraph', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['experiments.documents.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['experiments.equipment.id'], ),
    sa.ForeignKeyConstraint(['lab_id'], ['experiments.labs.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['experiments.materials.id'], ),
    sa.ForeignKeyConstraint(['regime_id'], ['experiments.regimes.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['experiments.researchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='experiments'
    )
    op.create_table('results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=True),
    sa.Column('property_id', sa.Uuid(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('proof_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiments.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['experiments.properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='experiments'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results', schema='experiments')
    op.drop_table('experiments', schema='experiments')
    op.drop_table('chat_message')
    op.drop_table('researchers', schema='experiments')
    op.drop_table('equipment', schema='experiments')
    op.drop_table('chat_session')
    op.drop_table('regimes', schema='experiments')
    op.drop_table('properties', schema='experiments')
    op.drop_table('materials', schema='experiments')
    op.drop_table('labs', schema='experiments')
    op.drop_table('ingest_tasks', schema='experiments')
    op.drop_table('entity_same_as', schema='experiments')
    op.drop_table('entity_aliases', schema='experiments')
    op.drop_table('documents', schema='experiments')
    # ### end Alembic commands ###
