/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWikiRouteImport } from './routes/_layout/wiki'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutReportsRouteImport } from './routes/_layout/reports'
import { Route as LayoutIngestRouteImport } from './routes/_layout/ingest'
import { Route as LayoutGraphRouteImport } from './routes/_layout/graph'
import { Route as LayoutGapsRouteImport } from './routes/_layout/gaps'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin.index'
import { Route as LayoutAdminCoverageRouteImport } from './routes/_layout/admin.coverage'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWikiRoute = LayoutWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReportsRoute = LayoutReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIngestRoute = LayoutIngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGraphRoute = LayoutGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGapsRoute = LayoutGapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminCoverageRoute = LayoutAdminCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => LayoutAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/chat': typeof LayoutChatRoute
  '/gaps': typeof LayoutGapsRoute
  '/graph': typeof LayoutGraphRoute
  '/ingest': typeof LayoutIngestRoute
  '/reports': typeof LayoutReportsRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/wiki': typeof LayoutWikiRoute
  '/admin/coverage': typeof LayoutAdminCoverageRoute
  '/admin/': typeof LayoutAdminIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/chat': typeof LayoutChatRoute
  '/gaps': typeof LayoutGapsRoute
  '/graph': typeof LayoutGraphRoute
  '/ingest': typeof LayoutIngestRoute
  '/reports': typeof LayoutReportsRoute
  '/search': typeof LayoutSearchRoute
  '/settings': typeof LayoutSettingsRoute
  '/wiki': typeof LayoutWikiRoute
  '/': typeof LayoutIndexRoute
  '/admin/coverage': typeof LayoutAdminCoverageRoute
  '/admin': typeof LayoutAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/gaps': typeof LayoutGapsRoute
  '/_layout/graph': typeof LayoutGraphRoute
  '/_layout/ingest': typeof LayoutIngestRoute
  '/_layout/reports': typeof LayoutReportsRoute
  '/_layout/search': typeof LayoutSearchRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/wiki': typeof LayoutWikiRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/coverage': typeof LayoutAdminCoverageRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/chat'
    | '/gaps'
    | '/graph'
    | '/ingest'
    | '/reports'
    | '/search'
    | '/settings'
    | '/wiki'
    | '/admin/coverage'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/chat'
    | '/gaps'
    | '/graph'
    | '/ingest'
    | '/reports'
    | '/search'
    | '/settings'
    | '/wiki'
    | '/'
    | '/admin/coverage'
    | '/admin'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/chat'
    | '/_layout/gaps'
    | '/_layout/graph'
    | '/_layout/ingest'
    | '/_layout/reports'
    | '/_layout/search'
    | '/_layout/settings'
    | '/_layout/wiki'
    | '/_layout/'
    | '/_layout/admin/coverage'
    | '/_layout/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/wiki': {
      id: '/_layout/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof LayoutWikiRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reports': {
      id: '/_layout/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof LayoutReportsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/ingest': {
      id: '/_layout/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof LayoutIngestRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/graph': {
      id: '/_layout/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof LayoutGraphRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/gaps': {
      id: '/_layout/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof LayoutGapsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/coverage': {
      id: '/_layout/admin/coverage'
      path: '/coverage'
      fullPath: '/admin/coverage'
      preLoaderRoute: typeof LayoutAdminCoverageRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminCoverageRoute: typeof LayoutAdminCoverageRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminCoverageRoute: LayoutAdminCoverageRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutGapsRoute: typeof LayoutGapsRoute
  LayoutGraphRoute: typeof LayoutGraphRoute
  LayoutIngestRoute: typeof LayoutIngestRoute
  LayoutReportsRoute: typeof LayoutReportsRoute
  LayoutSearchRoute: typeof LayoutSearchRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutWikiRoute: typeof LayoutWikiRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutChatRoute: LayoutChatRoute,
  LayoutGapsRoute: LayoutGapsRoute,
  LayoutGraphRoute: LayoutGraphRoute,
  LayoutIngestRoute: LayoutIngestRoute,
  LayoutReportsRoute: LayoutReportsRoute,
  LayoutSearchRoute: LayoutSearchRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutWikiRoute: LayoutWikiRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
